export const PERMISSOES = {
  GERENCIAR_USUARIOS: 'gerenciar_usuarios',
  VISUALIZAR_LOGS_AUDITORIA: 'visualizar_logs_auditoria',
  CONFIGURACOES_SISTEMA: 'configuracoes_sistema',
  GERENCIAR_INTEGRACOES_PAGAMENTO: 'gerenciar_integracoes_pagamento',
  GERENCIAR_PRODUTOS: 'gerenciar_produtos',
  GERENCIAR_TIPOS_PRODUTO: 'gerenciar_tipos_produto',
  GERENCIAR_TAMANHOS: 'gerenciar_tamanhos',
  GERENCIAR_CONDICOES: 'gerenciar_condicoes',
  GERENCIAR_DEPOSITOS: 'gerenciar_depositos',
  GERENCIAR_ROTAS: 'gerenciar_rotas',
  GERENCIAR_CLIENTES: 'gerenciar_clientes',
  TRANSFERIR_CLIENTE_ROTA: 'transferir_cliente_rota',
  CRIAR_EDITAR_LOCACAO: 'criar_editar_locacao',
  FINALIZAR_LOCACAO_DEPOSITO: 'finalizar_locacao_deposito',
  FINALIZAR_LOCACAO_RELOCACAO: 'finalizar_locacao_relocacao',
  EDITAR_REGRAS_LOCACAO: 'editar_regras_locacao',
  ALTERAR_CONTADOR_LOCACAO: 'alterar_contador_locacao',
  REGISTRAR_COBRANCA: 'registrar_cobranca',
  MARCAR_TROCA_PANO: 'marcar_troca_pano',
  VISUALIZAR_CLIENTES_TODAS_ROTAS: 'visualizar_clientes_todas_rotas',
  VISUALIZAR_PRODUTOS_DEPOSITO: 'visualizar_produtos_deposito',
  VISUALIZAR_RELATORIOS: 'visualizar_relatorios',
  EXPORTAR_RELATORIOS_PDF: 'exportar_relatorios_pdf',
  EXPORTAR_RELATORIOS_EXCEL: 'exportar_relatorios_excel',
  VISUALIZAR_RELATORIOS_OUTRAS_ROTAS: 'visualizar_relatorios_outras_rotas',
  USAR_IMPRESSAO_TERMICA: 'usar_impressao_termica',
} as const;

export type PermissaoChave = (typeof PERMISSOES)[keyof typeof PERMISSOES];
